// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD49nGDbgBIfaHDUw78aEyC_SuCKC3FHSQ',
    appId: '1:765974674867:web:37b02adc4dc1f10378dfc6',
    messagingSenderId: '765974674867',
    projectId: 'tmsflutter-e1485',
    authDomain: 'tmsflutter-e1485.firebaseapp.com',
    storageBucket: 'tmsflutter-e1485.firebasestorage.app',
    measurementId: 'G-G1V5FDQ9HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWn2oLC2s0xOLuM77DVXYX7skSTLMMyu4',
    appId: '1:765974674867:android:96528d9ee5322b2c78dfc6',
    messagingSenderId: '765974674867',
    projectId: 'tmsflutter-e1485',
    storageBucket: 'tmsflutter-e1485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3LiUFWwObkZRDkimEp771JCuSxjGIilk',
    appId: '1:765974674867:ios:e6830ef4a3516e1178dfc6',
    messagingSenderId: '765974674867',
    projectId: 'tmsflutter-e1485',
    storageBucket: 'tmsflutter-e1485.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3LiUFWwObkZRDkimEp771JCuSxjGIilk',
    appId: '1:765974674867:ios:e6830ef4a3516e1178dfc6',
    messagingSenderId: '765974674867',
    projectId: 'tmsflutter-e1485',
    storageBucket: 'tmsflutter-e1485.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD49nGDbgBIfaHDUw78aEyC_SuCKC3FHSQ',
    appId: '1:765974674867:web:ddb2a6930e4c3ba778dfc6',
    messagingSenderId: '765974674867',
    projectId: 'tmsflutter-e1485',
    authDomain: 'tmsflutter-e1485.firebaseapp.com',
    storageBucket: 'tmsflutter-e1485.firebasestorage.app',
    measurementId: 'G-1L5SHB8PQT',
  );
}
